name: Prettier
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: pnpm-setup
              uses: pnpm/action-setup@v3
              with:
                  version: 8
            - name: Set Node.js 18.x
              uses: actions/setup-node@v4
              with:
                  node-version: 18.x
                  cache: "pnpm"
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Check formatting with Prettier
              run: pnpm format:check
